{% set version = "8.1" %}
{% set name = "sagelib" %}
{% set variant = "openblas" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/sagemath/sage/archive/{{ version }}.tar.gz
  sha256: a42b55c2c8ac244535dc9b87171b7d4dd7e1d498099518ab253354fbe2eaaa7b
  patches:
    # sage patches cython to include sys.path, workaround that
    - patches/Fix-cython-bug.patch
    # don't do sanity checks as we are not in a source build
    - patches/sage-env.patch
    # disable sage-location since conda handles that and sage-location breaks
    # conda scripts
    - patches/disable-sage-location.patch
    # fix cython errors
    - patches/0001-Map._extra_slots-do-not-pass-dict.patch

build:
  number: 0
  skip: true  # [win]
  skip: true  # [py!=27]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - toolchain
    - libtool
    - automake
    - pip
    - setuptools
    - arb 2.11.*
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*
    - brial 1.2.*
    - cliquer 1.21
    - cypari2 >=1.1.4-1
    - cysignals 1.6.*
    - cython >=0.27
    - ecl 16.1.*
    - eclib >=20171002
    - ecm 7.*
    - future
    - givaro 4.0.*
    - glpk 4.65.*
    - gmp >=5.0.1,<7
    - gsl 2.4.*
    - iml 1.0.*
    - jinja2 2.9.*
    - lcalc 1.23
    - lrcalc 1.2
    - libflint 2.5.*
    - libgap 4.8.6
    - libgd 2.2.*
    - libpng >=1.6.29,<1.7
    - linbox 1.4.*
    - m4ri >=20140914
    - m4rie >=20150908
    - mpc 1.0.*
    - mpfi 1.5.*
    - mpfr 3.*
    - ntl 10.3.*
    - numpy 1.13.*
    - pari 2.9.*
    - pkgconfig
    - planarity 3.*
    - ppl 1.2
    - pynac 0.7.17
    - python
    - ratpoints 2.1.*
    - readline 6.2*
    - rw 0.7
    - singular 4.1.*
    - six
    - symmetrica 2.0
    - zn_poly 0.9
    # sageruntime deps
    - ipython >=5
    - psutil >=5
    - pexpect >=4

  run:
    - arb 2.11.*
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*
    - brial 1.2.*
    - cliquer 1.21
    - cypari2 1.1.*
    - cysignals 1.6.*
    - cython >=0.27
    - ecl 16.1.*
    - eclib >=20171002
    - ecm 7.*
    - future
    - givaro 4.0.*
    - glpk 4.65.*
    - gmp >=5.0.1,<7
    - gsl 2.4.*
    - iml 1.0.*
    - jinja2 2.9.*
    - lcalc 1.23
    - lrcalc 1.2
    - libflint 2.5.*
    - libgap 4.8.6
    - libgd 2.2.*
    - libpng >=1.6.29,<1.7
    - linbox 1.4.*
    - m4ri >=20140914
    - m4rie >=20150908
    - mpc 1.0.*
    - mpfi 1.5.*
    - mpfr 3.*
    - ntl 10.3.*
    - numpy >=1.13
    - pari 2.9.*
    - pkgconfig
    - planarity 3.*
    - ppl 1.2
    - pynac 0.7.17
    - python
    - ratpoints 2.1.*
    - readline 6.2*
    - rw 0.7
    - singular 4.1.*
    - six
    - symmetrica 2.0
    - zn_poly 0.9
    # sageruntime deps
    - ipython >=5
    - psutil >=5
    - pexpect >=4

test:
  imports:
    - sage
  commands:
    - sage -v

about:
  home: https://www.sagemath.org
  license: GPLv2+
  license_file: COPYING.txt
  summary: Open Source Mathematical Software
  dev_url: https://trac.sagemath.org
  doc_url: https://doc.sagemath.org

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
