travis:
  secure:
    BINSTAR_TOKEN: p2jHuKF24ot0YpWUnnUjMyzEWbZNziUXq03SI/gRres/dH/baQ/UFOdDxJ6zBgAIXcAAVZfyj+8TDPPCVzYZzrArcPNZ7E9Q7CJN53O44Ok/D5RJWHFQFCFH3UUSsZVBXuechUBRH8FodqcEGK2vz2d+TKaIcDh1ZtmAo4NcO+lfoFrGBd2eHtEfzwKd6ccBVW86qzns2y3R58y09hveSDebhMyIytJizgmw6+34ozJidAiMiaRhuz+tzHbDFuuPIfFM/oaaC+b78GciMCb/ZC3YeG0Bbgi/VSNuxOwWdhZT2qBHExP3MtrGiLa7zBA6hVg1UqqZFhVKNRVqQyXpq0jdBagXbUAoA6H0+I4yrt2kY2GxeInY4l0NnxlbOnf9qfbN8lbx6QTusimSCyohDgIFlwy4tEpJffrKKww35BdKvUKwEvQ3gXmoiTzWMkGvBmT8oce28TTfk2NSuW8y3Sfr3+/PRQuGR3craif7KoNRS4IZSVMpAwqAyDHlhpdRVPV/Qctm04/6aX2AUM1NzTHUdGrB4YbQQionvwvZGvRBlfbJ3qNvnNFQoIrhYaMIqzkk+jEzplMavg8cJiV23/NO/7qETbzDcGsxrWrl/xCu2dWQqKWbmzlGbWldrgHTh/uVrjd69y2gdUUu7uBMdS0EB1H7YakeAmh5w+1BKtg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
