travis:
  secure:
    BINSTAR_TOKEN: Ma3bUElw9mWdw2CCyZ3xPCsIs7T6SC/SIZem2cdsOXIGBx2wJvk4M7dByXfA7mwd/MOdUq1AKUkrOLy9ogSKaqtNOqwY/9G9RtO6o5X3R2acJgoFO0A1duPexadK6pDQ7ZFCvhamLoSvvBkK+CWxZ0YdWnr686Qaiuu3z5IsVqmWngfAsbf4XN48wuQ1YZ4uCyGEB3Vg2vYpCjXONHnodJPKLUfn6bHZVNjNPYC3oEX77lq9OByPgegTMgkJJUXZ5fDZU5o95StxmbcMBnSV0iOUrktOFWj+gkYrNeEmNJxmLWcff1xjzrBCsDZ/4FhEs64Nun9+B/7eU4LAwWEDHH0gZOtRht+C0Cbmq5DGjn1ew4t2CL9s1JHzogEF1Y6LsYQJgS8nAmkRk0OWeB+2iWYFM+IlICfaMMpEiFM3LprPqZgFGWdlMrgO99hLxRtkjd9JJy3scA1RY3LUMLskqvPKve7P6qMh5p5+vi3R4RzApX72mhAUCmIG5JHBdVa4z891ByrBQCPVlIkh9D1QxrgED8+oSXwtD5apdI1VOxN/wZSjMXNByIO3LCC/dxiDaYQWzpNno48H2FcpXytYttGhxU8mUwzcG8HDhc9KDWIk7Tk+H8g26XVTLt2csOqrBme/trqu0ZGi4RCHMcGyfZIMTXZSwHFZl0fvL/3bauc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
provider:
  osx: circle
